import { useCallback, useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate, useParams } from "react-router-dom";
import { CompareView } from "../components/CompareView";
import { applyChoice, createSortState, estimateComparisons, getCurrentPair, type SortChoice } from "../lib/sorter";
import { clearSession, getDecision, getSession, saveSession, updateDecision } from "../lib/storage";
import { createId, getOptionLabel, shuffle } from "../lib/utils";
import type { Comparison, DecisionSession } from "../types";
export default function ComparePage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const [decision] = useState(() => getDecision(id));
  const [session, setSession] = useState<DecisionSession | null>(() => { const existing = getSession(id); if (existing) return existing; const stored = getDecision(id); if (!stored || stored.ranking) return null; const created = { decisionId: id, sorter: createSortState(shuffle(stored.options.map((option) => option.id))), comparisons: [], undoStack: [] }; saveSession(created); return created; });
  const [selected, setSelected] = useState<SortChoice | null>(null); const [locked, setLocked] = useState(false); const pair = useMemo(() => session && getCurrentPair(session.sorter), [session]); const total = estimateComparisons(decision?.options.length ?? 0);
  const choose = useCallback((choice: SortChoice) => { if (!session || !decision || !pair || locked) return; setLocked(true); setSelected(choice); const comparison: Comparison = { id: createId(), leftId: pair.leftId, rightId: pair.rightId, winnerId: choice === "left" ? pair.leftId : choice === "right" ? pair.rightId : null, createdAt: Date.now() }; const nextSorter = applyChoice(session.sorter, choice); const nextSession = { ...session, sorter: nextSorter, comparisons: [...session.comparisons, comparison], undoStack: [...session.undoStack, { sorter: session.sorter, comparisons: session.comparisons }] }; saveSession(nextSession); if (nextSorter.done) updateDecision(decision.id, { comparisons: nextSession.comparisons, ranking: nextSorter.ranking, completedAt: Date.now() }); window.setTimeout(() => { if (nextSorter.done) { clearSession(decision.id); navigate(`/decision/${decision.id}/reveal`); return; } setSession(nextSession); setSelected(null); setLocked(false); }, 190); }, [decision, locked, navigate, pair, session]);
  const undo = useCallback(() => { if (!session || locked) return; const last = session.undoStack.at(-1); if (!last) return; const restored = { ...session, sorter: last.sorter, comparisons: last.comparisons, undoStack: session.undoStack.slice(0, -1) }; setSession(restored); saveSession(restored); }, [locked, session]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "z") { event.preventDefault(); undo(); } else if (event.key === "ArrowLeft" || event.key === "1") choose("left"); else if (event.key === "ArrowRight" || event.key === "2") choose("right"); else if (event.key === "Escape") navigate("/"); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [choose, navigate, undo]);
  if (!decision) return <Navigate replace to="/" />; if (!session && decision.ranking) return <Navigate replace to={`/decision/${decision.id}/results`} />; if (!session || !pair) return null;
  return <CompareView title={decision.title} left={getOptionLabel(decision, pair.leftId)} right={getOptionLabel(decision, pair.rightId)} progress={total ? Math.min(100, session.comparisons.length / total * 100) : 0} current={session.comparisons.length + 1} total={total} selected={selected} locked={locked} canUndo={session.undoStack.length > 0} onChoose={choose} onUndo={undo} />;
}
