import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')

const output = resolve('output')
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
const errors = []
const watch = (page) => page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })

const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
watch(page)
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
await page.screenshot({ path: resolve(output, '01-login-desktop.png'), fullPage: true })
await page.getByRole('button', { name: /Continue in demo mode/ }).click()
await page.getByLabel('Private message').waitFor()
await page.screenshot({ path: resolve(output, '02-create-desktop.png'), fullPage: true })
await page.getByLabel('Private message').fill('The Wi-Fi password is:\n\ncoffee-before-code')
await page.getByLabel('Give it a name').fill('Apartment Wi-Fi')
await page.getByRole('button', { name: /Create private link/ }).click()
await page.getByRole('heading', { name: 'Your link is ready.' }).waitFor()
await page.getByRole('button', { name: 'Show link' }).click()
const shareUrl = await page.getByTestId('share-link').innerText()
await page.screenshot({ path: resolve(output, '03-ready-desktop.png'), fullPage: true })
await page.goto(shareUrl, { waitUntil: 'networkidle' })
await page.getByRole('button', { name: /Reveal message/ }).waitFor()
await page.screenshot({ path: resolve(output, '04-pre-reveal-desktop.png'), fullPage: true })
await page.getByRole('button', { name: /Reveal message/ }).click()
await page.getByText('coffee-before-code', { exact: false }).waitFor()
await page.screenshot({ path: resolve(output, '05-revealed-desktop.png'), fullPage: true })
await page.reload()
await page.getByRole('button', { name: /Reveal message/ }).click()
await page.getByRole('heading', { name: 'This message is gone.' }).waitFor()
await page.screenshot({ path: resolve(output, '06-gone-desktop.png'), fullPage: true })
await page.setViewportSize({ width: 375, height: 812 })
await page.goto('http://localhost:5173/history', { waitUntil: 'networkidle' })
await page.getByRole('heading', { name: 'History' }).waitFor()
await page.waitForTimeout(350)
await page.screenshot({ path: resolve(output, '08-history-mobile.png') })

const mobile = await browser.newPage({ viewport: { width: 375, height: 812 } })
watch(mobile)
await mobile.goto('http://localhost:5173', { waitUntil: 'networkidle' })
await mobile.getByRole('button', { name: /Continue in demo mode/ }).click()
await mobile.getByLabel('Private message').waitFor()
await mobile.waitForTimeout(350)
await mobile.screenshot({ path: resolve(output, '07-create-mobile.png') })

await browser.close()
if (errors.length) throw new Error(`Console errors: ${errors.join(' | ')}`)
console.log(`Verified critical flow; screenshots: ${output}`)
