import { AnimatePresence, motion } from "motion/react";
import { ChoiceCard } from "./ChoiceCard";
import { AppHeader } from "./Chrome";
import type { SortChoice } from "../lib/sorter";

type Props = { title: string; left: string; right: string; progress: number; current: number; total: number; selected: SortChoice | null; locked: boolean; canUndo: boolean; onChoose: (choice: SortChoice) => void; onUndo: () => void };

export function CompareView({ title, left, right, progress, current, total, selected, locked, canUndo, onChoose, onUndo }: Props) {
  return <div className="min-h-screen bg-[#fafafa] dark:bg-[#0b0b0b]"><AppHeader mode="compare" title={title} closeTo="/" /><div className="h-px bg-[#ededed] dark:bg-[#222]"><motion.div animate={{ width: `${progress}%` }} className="h-full bg-[#111] dark:bg-white" /></div><main className="mx-auto flex min-h-[calc(100vh-65px)] w-full max-w-[920px] flex-col justify-center px-4 py-12 md:px-8 md:py-16"><div className="mb-8 text-center"><span className="mb-3 block text-[9px] font-semibold uppercase tracking-[0.15em] text-[#8a8a8a]">{Math.min(current, total)} of {total}</span><h1 className="text-[29px] font-semibold tracking-[-0.04em] text-[#111] dark:text-white md:text-[36px]">Which would you pick?</h1></div><AnimatePresence mode="wait"><motion.div key={`${left}-${right}-${current}`} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} className="relative grid grid-cols-1 gap-4 md:grid-cols-2 md:gap-7"><ChoiceCard side="A" title={left} selected={selected === "left"} dimmed={selected === "right"} disabled={locked} helper={selected === "left" ? "Selected" : "Tap to choose"} shortcut="← Key" onClick={() => onChoose("left")} /><span className="absolute left-1/2 top-1/2 z-10 flex size-8 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-[#e1e1e1] bg-[#fafafa] text-[9px] font-semibold uppercase text-[#717171] dark:border-[#292929] dark:bg-[#0b0b0b]">or</span><ChoiceCard side="B" title={right} selected={selected === "right"} dimmed={selected === "left"} disabled={locked} helper={selected === "right" ? "Selected" : "Tap to choose"} shortcut="→ Key" onClick={() => onChoose("right")} /></motion.div></AnimatePresence><div className="mt-8 flex flex-col items-center gap-5"><button type="button" disabled={locked} onClick={() => onChoose("tie")} className="text-[11px] text-[#717171] underline-offset-4 hover:text-[#111] hover:underline disabled:opacity-40 dark:hover:text-white">Can't decide</button><div className="flex gap-4 text-[9px] text-[#9a9a9a]"><span>Use ← → to choose</span>{canUndo && <><span>·</span><button type="button" onClick={onUndo}>Undo ⌘Z</button></>}</div></div></main></div>;
}
