import { ChevronRight } from "lucide-react";
import { Link } from "react-router-dom";
import { AppHeader, Footer } from "./Chrome";
import { getOptionLabel, formatRelativeTime } from "../lib/utils";
import type { Category, Decision } from "../types";
type Filter = "All" | Exclude<Category, "General">;
const filters: Filter[] = ["All", "Food", "Tech", "Work"];
const sparks = ["What should I eat?", "Which laptop?", "Where should we go?", "What should I build?"];
export function HistoryView({ decisions, filter, visible, onFilter, onMore, onNew }: { decisions: Decision[]; filter: Filter; visible: number; onFilter: (filter: Filter) => void; onMore: () => void; onNew: (title?: string) => void }) {
  if (!decisions.length) return <div className="flex min-h-screen flex-col bg-[#fafafa] dark:bg-[#0b0b0b]"><AppHeader historyActive /><main className="flex flex-1 flex-col items-center justify-center px-4 text-center"><h1 className="text-[25px] font-semibold text-[#111] dark:text-white">Nothing decided yet.</h1><p className="mt-2 max-w-[360px] text-[11px] leading-5 text-[#717171]">Your questionable life choices will appear here once you run your first comparison.</p><button type="button" onClick={() => onNew()} className="mt-6 h-11 rounded-xl bg-[#111] px-6 text-[12px] font-medium text-white dark:bg-white dark:text-[#111]">Make a decision →</button><div className="mt-10 flex max-w-[460px] flex-wrap justify-center gap-2"><span className="mb-1 w-full text-[8px] font-semibold uppercase tracking-[0.12em] text-[#999]">Quick sparks</span>{sparks.map((spark) => <button key={spark} type="button" onClick={() => onNew(spark)} className="rounded-full border border-[#e1e1e1] bg-white px-3 py-1.5 text-[9px] text-[#717171] dark:border-[#292929] dark:bg-[#121212]">{spark}</button>)}</div></main><Footer /></div>;
  const filtered = filter === "All" ? decisions : decisions.filter((decision) => decision.category === filter);
  return <div className="flex min-h-screen flex-col bg-[#fafafa] dark:bg-[#0b0b0b]"><AppHeader historyActive /><main className="mx-auto w-full max-w-[1080px] flex-1 px-4 py-10 md:px-8"><div className="mx-auto max-w-[620px]"><h1 className="text-[29px] font-semibold tracking-[-0.04em] text-[#111] dark:text-white">Past decisions</h1><p className="mt-1 text-[11px] text-[#717171]">Your questionable life choices, remembered.</p><div className="mt-5 flex gap-2">{filters.map((item) => <button key={item} type="button" onClick={() => onFilter(item)} className={`rounded-full border px-3 py-1 text-[9px] font-medium ${filter === item ? "border-[#111] bg-[#111] text-white dark:border-white dark:bg-white dark:text-[#111]" : "border-[#e1e1e1] bg-white text-[#717171] dark:border-[#292929] dark:bg-[#121212]"}`}>{item}</button>)}</div><div className="mt-6 space-y-2.5">{filtered.slice(0, visible).map((decision) => { const winner = decision.ranking?.[0] ? getOptionLabel(decision, decision.ranking[0]) : "No winner"; return <Link key={decision.id} to={`/decision/${decision.id}/results`} className="group flex min-h-[72px] items-center justify-between rounded-xl border border-[#e1e1e1] bg-white px-4 dark:border-[#292929] dark:bg-[#121212]"><div className="min-w-0"><h2 className="truncate text-[13px] font-medium text-[#111] dark:text-white">{decision.title}</h2><div className="mt-2 flex flex-wrap items-center gap-2 text-[8px] text-[#8a8a8a]"><span className="rounded-full bg-[#111] px-2 py-0.5 font-medium text-white dark:bg-white dark:text-[#111]">{decision.category}</span><span>{winner} won</span><span>·</span><span>{decision.options.length} options</span><span>·</span><span>{formatRelativeTime(decision.completedAt)}</span></div></div><ChevronRight size={15} className="text-[#b0b0b0]" /></Link>})}</div>{filtered.length > visible && <button type="button" onClick={onMore} className="mt-6 w-full text-center text-[10px] text-[#717171]">Load more</button>}</div></main><Footer /></div>;
}
